os: linux
dist: xenial
language: python
python: 3.7

install: pip install -e ".[test]"
script:
  - bash tests/tests.sh
  - pytest

jobs:
  include:
    - stage: test

    - stage: deploy
      if: tag IS present AND repo = cmla/rpcm
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: carlodef
          password:
              secure: "qTN2mT3LGMZQdnYyZrGHtH5KktRSHnV2L41C3Phl6YmLu15B7u9zoY1cnoLDYgnoKRzySItoXhOFX6teMb0V/N/W8yPXiQ8yPqoeu/aTEJlESFHK3J0kSufJRTxFnmD0gNLEudYVpCkAQsJIq9v+EEu4k0tflJH2s6uHdJg1TTuzkePtMDrKFHyhbp4vMg3ySIUSjmI3T+c9x6due81qcY7+50m5A0EnTPfE7VaR1Hci61pQsLNDUs4SMoEyStjY2PecOm1Pu73t14Kq1JLFio/OgrF0GrS8DwzJn7NChiWj/nSa/Eea7Q5po9yMtqkgqTZbwnfYEs1ELOzqidan/zRgrennOy0g/MghZQfw7hzEpcaMRgKyltaaGa5uOyXsPp8laacfinN6uxtEuMpLWfpmkwObSsQQGlAETKJEPIT7+7ogp0mhk10qBQzVf0tdc9hfXGLTQXmlBourG4fGad25pehhkmEPeZrbdrb9Bl4bG0bwIyqVxoPZAeDXcRBWqZeTnOfeHUBB+PS9i8FVZ/9Nr9GkrQTFaWM3MMvSigWAAHFgOFmGyEpTI5CYKNzOdnAUqKpZMbf0wZ8uXc6IVHrbKFeDezulOMaR1anmCV8JVSQK5MiJkan+UMJVnTaGRk9BRhtcGOolQ96oqPWwLXl/q7/S5VwzTYejQNfq7Hg="
          distributions: sdist bdist_wheel
          on:
            tags: true
